# Generated by Django 5.2.7 on 2025-11-11 16:00

from django.db import migrations

import phonenumbers


def _normalize_first_valid(raw: str, default_region: str = "RU"):
    """Возвращает первый валидный номер в формате E.164 из строки raw."""
    if not raw:
        return None

    s = str(raw).strip()
    try:
        num = phonenumbers.parse(s, default_region)
        if phonenumbers.is_valid_number(num):
            return phonenumbers.format_number(num, phonenumbers.PhoneNumberFormat.E164)
    except phonenumbers.NumberParseException:
        pass

    for match in phonenumbers.PhoneNumberMatcher(s, default_region):
        if phonenumbers.is_valid_number(match.number):
            return phonenumbers.format_number(match.number, phonenumbers.PhoneNumberFormat.E164)

    return None


def forwards(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    qs = Flat.objects.all().only("id", "phone", "owner_pure_phone").iterator(chunk_size=1000)
    to_update = []
    for obj in qs:
        normalized = _normalize_first_valid(obj.phone, "RU")
        if normalized and obj.owner_pure_phone != normalized:
            obj.owner_pure_phone = normalized
            to_update.append(obj)
        if len(to_update) >= 1000:
            Flat.objects.bulk_update(to_update, ["owner_pure_phone"])
            to_update.clear()
    if to_update:
        Flat.objects.bulk_update(to_update, ["owner_pure_phone"])


def backwards(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    Flat.objects.update(owner_pure_phone=None)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_alter_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
