# Generated by Django 5.2.7 on 2025-11-13 15:16

from django.db import migrations


def move_owners_forward(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for flat in Flat.objects.all():
        if not flat.owner:
            continue

        owner, created = Owner.objects.get_or_create(
            name=flat.owner,
            phonenumber=getattr(flat, 'owners_phonenumber', ''),
            pure_phone=getattr(flat, 'owner_pure_phone', ''),
        )
        owner.flats.add(flat)


def move_owners_backward(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for owner in Owner.objects.all():
        for flat in owner.flats.all():
            flat.owner = owner.name
            if hasattr(flat, 'owners_phonenumber'):
                flat.owners_phonenumber = owner.phonenumber
            if hasattr(flat, 'owner_pure_phone'):
                flat.owner_pure_phone = owner.pure_phone
            flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_owner'),
    ]

    operations = [
        migrations.RunPython(move_owners_forward, move_owners_backward),
    ]
