# Generated by Django 5.2.7 on 2025-11-13 15:22

from django.db import migrations


def link_flats_to_owners(apps, schema_editor):
    """Переносим данные из полей Flat.owner / owners_phonenumber / owner_pure_phone
    в связь Owner.flats.

    Миграция написана так, чтобы её можно безопасно запускать повторно.
    """
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for flat in Flat.objects.all():
        # Старые поля в модели Flat
        raw_name = getattr(flat, 'owner', None)
        raw_phone = getattr(flat, 'owners_phonenumber', None)
        raw_pure = getattr(flat, 'owner_pure_phone', None)

        name = str(raw_name).strip() if raw_name else ''
        phone = str(raw_phone).strip() if raw_phone else ''
        pure = str(raw_pure).strip() if raw_pure else ''

        # Если вообще нет данных о владельце — пропускаем
        if not (name or phone or pure):
            continue

        # Ищем/создаём владельца
        owner, created = Owner.objects.get_or_create(
            name=name,
            phonenumber=phone,
            pure_phone=pure,
        )

        # Собираем уже привязанные квартиры
        existing_ids = set(owner.flats.values_list('id', flat=True))
        # Добавляем текущую
        existing_ids.add(flat.id)

        # .set() делает миграцию идемпотентной: при повторном запуске
        # состав связи просто пересоберётся из множества ID
        owner.flats.set(Flat.objects.filter(id__in=existing_ids))


def unlink_flats_from_owners(apps, schema_editor):
    """Обратная миграция: если старые поля в Flat ещё существуют,
    заполняем их из первого владельца.
    """
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for owner in Owner.objects.all():
        for flat in owner.flats.all():
            # Ничего не перезатираем, если там уже что-то руками написано
            if hasattr(flat, 'owner') and not getattr(flat, 'owner', None):
                flat.owner = owner.name
            if hasattr(flat, 'owners_phonenumber') and not getattr(flat, 'owners_phonenumber', None):
                flat.owners_phonenumber = owner.phonenumber
            if hasattr(flat, 'owner_pure_phone') and not getattr(flat, 'owner_pure_phone', None):
                flat.owner_pure_phone = owner.pure_phone
            flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_move_flat_owners_to_owner_model'),
    ]

    operations = [
        migrations.RunPython(link_flats_to_owners, unlink_flats_from_owners),
    ]
